version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/samplepython
hooks:
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
