version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/samplepython

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ubuntu
